name = "modoru: create"
author = "justlofe, orisana"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "530d33501dda203e36aa07313821519ec69503e7b5f19877b7297148fb8f654c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
