name = "modoru: create"
author = "justlofe, orisana"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2193c05f38249a18a8884f3ae82aa08e56a9733ca9ca50ce76b7d7bfe5e3f3d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
