name = "modoru: create"
author = "justlofe, orisana"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0eb5403fdf6e5bac392a9e285849177ff20bb41a2cc4b48310de17e31d173bb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
