plugins {
    id("java-library")
    id("idea")
    id("net.neoforged.moddev").version("2.0.143")
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
    maven { url = "https://maven.createmod.net" }
    maven { url = "https://maven.ithundxr.dev/snapshots" }

    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

base {
    archivesName = "modoru_create"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            systemProperty("neoforge.enabledGameTestNamespaces", project.mod_id)
        }

        server {
            server()
            programArgument("--nogui")
            systemProperty("neoforge.enabledGameTestNamespaces", project.mod_id)
        }

        configureEach {
            systemProperty("forge.logging.markers", "REGISTRIES")
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources {
    srcDir("src/generated/resources")
}

dependencies {
    implementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    implementation("com.tterrag.registrate:Registrate:${registrate_version}")
    implementation("maven.modrinth:ocEZ7tc1:${ftbchecker_modrinth_version_id}") // FTBChecker
}


tasks {
    processResources {
        var replaceProperties = [minecraft_version       : minecraft_version,
                                 minecraft_version_range : minecraft_version_range,
                                 neo_version             : neo_version,
                                 neo_version_range       : neo_version_range,
                                 loader_version_range    : loader_version_range,
                                 mod_id                  : mod_id,
                                 mod_version             : mod_version,
                                 ftbchecker_version_range: ftbchecker_version_range]
        inputs.properties(replaceProperties)

        filesMatching("META-INF/neoforge.mods.toml") {
            expand(replaceProperties)
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
